### PR TITLE
2022 03 23 updating shiny dashboards from excel via mongodb the good the bad and the shiny

### PR DESCRIPTION
**Pull request by MarkMc1089**
The only conflict is in `install.R` - I ordered the list to make it easier to see what is already there

### CODE REVIEW

**Comment by MarkMc1089** [comment]
I forgot to pull to my local repo before branching. Had a LOT of updates since then. I've resolved them all I think, so good to merge if you are happy with it?

**Comment by MWilson92** [comment]
@MarkMc1089 when i try to run the app from app.R i'm getting this error
image
does the app run for you?

**Comment by MarkMc1089** [comment]
When I try to visit the binder on this branch I am getting "503 Service Temporarily Unavailable". There is a problem with running the app locally in the C&C repo. It works fine in my own repo. I basically copied everything except the R project file and .git folder into the C&C folder for my session.

My plan is to give the link for the original repo for anyone who wants to try it out. But at least the code is there in the C&C repo for non-interactive viewing.

**Comment by MWilson92** [comment]
> When I try to visit the binder on this branch I am getting "503 Service Temporarily Unavailable". There is a problem with running the app locally in the C&C repo. It works fine in my own repo. I basically copied everything except the R project file and .git folder into the C&C folder for my session.
> 
> My plan is to give the link for the original repo for anyone who wants to try it out. But at least the code is there in the C&C repo for non-interactive viewing.

I'll approve and merge close to session happening now but will need to look into why it's playing up.

**Review by MWilson92 — APPROVED** [review]

**Pull request merged**
